{
 "title": "Kepler Power Monitoring - Cost & Carbon",
 "tags": [
  "kepler",
  "power-monitoring",
  "sustainability",
  "carbon"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "tibber_ds",
    "label": "Tibber Data Source",
    "query": "yesoreyeram-infinity-datasource"
   },
   {
    "name": "emaps_ds",
    "label": "Electricity Maps Data Source",
    "query": "yesoreyeram-infinity-datasource"
   },
   {
    "name": "price_zone",
    "label": "Price Zone",
    "query": {}
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kepler_pod_cpu_joules_total, node_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_pod_cpu_joules_total, pod_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "electricity_price", "label": "Electricity Price (SEK/kWh)", "query": "1.00" },
   { "name": "carbon_intensity", "label": "Carbon Intensity (gCO2eq/kWh)", "query": "45" }
  ]
 },
 "panels": [
  {
   "title": "Overview - Real-time Power Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster Power (Watts)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kepler_pod_cpu_joules_total[1m]))",
     "legendFormat": "Cluster Total"
    }
   ]
  },
  {
   "title": "Cluster Energy (kWh/24h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kepler_pod_cpu_joules_total[24h])) / 3600000",
     "legendFormat": "24h Total"
    }
   ]
  },
  {
   "title": "Cluster Cost (24h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(kepler_pod_cpu_joules_total[24h])) / 3600000) * ${electricity_price}",
     "legendFormat": "24h Cost"
    }
   ]
  },
  {
   "title": "CO2eq Emissions (24h) @ ${carbon_intensity} gCO2eq/kWh",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(kepler_pod_cpu_joules_total[24h])) / 3600000) * ${carbon_intensity}",
     "legendFormat": "CO2eq (24h)"
    }
   ]
  },
  { "title": "Node Level Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Power by Node (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (node_name) (irate(kepler_pod_cpu_joules_total{node_name=~\"$node\"}[1m]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Power Distribution by Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node_name) (irate(kepler_pod_cpu_joules_total{node_name=~\"$node\"}[1m]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Namespace Level Power & Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Power by Namespace (Watts) - Stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pod_namespace) (irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{pod_namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Power, Cost & CO2eq Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (pod_namespace) (irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\"}[24h])) / 3600000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\"}[24h])) / 3600000) * ${electricity_price}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\"}[24h])) / 3600000) * ${carbon_intensity}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod Level Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Top 15 Pods by Power (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "topk(15, sum by (pod_name, pod_namespace) (irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m])))",
     "legendFormat": "{{pod_namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Power, Cost & CO2eq Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (pod_name, pod_namespace) (irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod_name, pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h])) / 3600000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (pod_name, pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h])) / 3600000) * ${electricity_price}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (pod_name, pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h])) / 3600000) * ${carbon_intensity}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Component Breakdown (Package vs DRAM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Power by Component (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\", zone=\"package\"}[1m]))",
     "legendFormat": "CPU (Package)"
    },
    {
     "expr": "sum(irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\", zone=\"dram\"}[1m]))",
     "legendFormat": "DRAM (Memory)"
    }
   ]
  },
  {
   "title": "Power Component Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\", zone=\"package\"}[1m]))",
     "legendFormat": "CPU (Package)"
    },
    {
     "expr": "sum(irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\", zone=\"dram\"}[1m]))",
     "legendFormat": "DRAM (Memory)"
    }
   ]
  },
  {
   "title": "Virtual Machine Power (OpenShift Virtualization)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "Virtual Machine Power (virt-launcher pods)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pod_name, pod_namespace) (irate(kepler_pod_cpu_joules_total{pod_name=~\"virt-launcher.*\", pod_namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{pod_namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "VM Power, Cost & CO2eq Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by (pod_name, pod_namespace) (irate(kepler_pod_cpu_joules_total{pod_name=~\"virt-launcher.*\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod_name, pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_name=~\"virt-launcher.*\"}[24h])) / 3600000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (pod_name, pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_name=~\"virt-launcher.*\"}[24h])) / 3600000) * ${electricity_price}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (pod_name, pod_namespace) (increase(kepler_pod_cpu_joules_total{pod_name=~\"virt-launcher.*\"}[24h])) / 3600000) * ${carbon_intensity}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Carbon & Cost Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Daily CO2eq Emissions @ ${carbon_intensity} gCO2eq/kWh",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h])) / 3600000) * ${carbon_intensity}",
     "legendFormat": "CO2eq Emissions"
    }
   ]
  },
  {
   "title": "CO2eq Emission Rate Over Time @ ${carbon_intensity} gCO2eq/kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "expr": "(sum(irate(kepler_pod_cpu_joules_total{pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m])) / 1000) * ${carbon_intensity}",
     "legendFormat": "CO2eq Rate (gCO2eq/hour)"
    }
   ]
  },
  {
   "title": "Live Carbon Intensity (Electricity Maps - ${price_zone})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }
  },
  {
   "title": "Live Carbon Intensity (${price_zone})",
   "type": "stat",
   "description": "Live carbon intensity from Electricity Maps API for SE-SE3 (Sweden)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "carbonIntensity", "text": "carbonIntensity", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.electricitymaps.com/v3/carbon-intensity/latest?zone=SE-${price_zone}",
     "url_options": { "method": "GET" }
    }
   ]
  },
  {
   "title": "Fossil Free % (${price_zone})",
   "type": "stat",
   "description": "Fossil-free percentage in the current electricity mix (higher is better)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "fossilFreePercentage", "text": "fossilFreePercentage", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.electricitymaps.com/v3/power-breakdown/latest?zone=SE-${price_zone}",
     "url_options": { "method": "GET" }
    }
   ]
  },
  {
   "title": "Renewable % (${price_zone})",
   "type": "stat",
   "description": "Renewable energy percentage in the current electricity mix",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "renewablePercentage", "text": "renewablePercentage", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.electricitymaps.com/v3/power-breakdown/latest?zone=SE-${price_zone}",
     "url_options": { "method": "GET" }
    }
   ]
  },
  {
   "title": "Tibber Electricity Prices (${price_zone})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "title": "Current Price (SEK/kWh)",
   "type": "stat",
   "description": "Current electricity price from Tibber API",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "root_selector": "data.viewer.homes.0.currentSubscription.priceInfo.current",
     "source": "url",
     "type": "graphql",
     "url": "https://api.tibber.com/v1-beta/gql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{ viewer { homes { currentSubscription { priceInfo { current { total level startsAt } } } } } }",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Price Level",
   "type": "stat",
   "description": "Current price level from Tibber (based on 3-day moving average)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "root_selector": "data.viewer.homes.0.currentSubscription.priceInfo.current",
     "source": "url",
     "type": "graphql",
     "url": "https://api.tibber.com/v1-beta/gql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{ viewer { homes { currentSubscription { priceInfo { current { total level startsAt } } } } } }",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Today & Tomorrow Hourly Prices (SEK/kWh)",
   "type": "timeseries",
   "description": "Today's hourly electricity prices from Tibber",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "startsAt", "text": "time", "type": "timestamp" },
      { "selector": "total", "text": "total", "type": "number" }
     ],
     "root_selector": "data.viewer.homes.0.currentSubscription.priceInfo.today",
     "source": "url",
     "type": "graphql",
     "url": "https://api.tibber.com/v1-beta/gql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{ viewer { homes { currentSubscription { priceInfo { today { total startsAt level } tomorrow { total startsAt level } } } } } }",
      "method": "POST"
     }
    },
    {
     "columns": [
      { "selector": "startsAt", "text": "time", "type": "timestamp" },
      { "selector": "total", "text": "total", "type": "number" }
     ],
     "root_selector": "data.viewer.homes.0.currentSubscription.priceInfo.tomorrow",
     "source": "url",
     "type": "graphql",
     "url": "https://api.tibber.com/v1-beta/gql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{ viewer { homes { currentSubscription { priceInfo { today { total startsAt level } tomorrow { total startsAt level } } } } } }",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Today's Hourly Prices",
   "type": "table",
   "description": "Today's hourly electricity prices with price levels",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "columns": [
      { "selector": "startsAt", "text": "startsAt", "type": "timestamp" },
      { "selector": "total", "text": "total", "type": "number" },
      { "selector": "level", "text": "level", "type": "string" }
     ],
     "root_selector": "data.viewer.homes.0.currentSubscription.priceInfo.today",
     "source": "url",
     "type": "graphql",
     "url": "https://api.tibber.com/v1-beta/gql",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "{ viewer { homes { currentSubscription { priceInfo { today { total startsAt level } } } } } }",
      "method": "POST"
     }
    }
   ]
  }
 ]
}